version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_play_scala_productos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
